<template>
  <main class="portal teacher-portal">
    <header class="top"><div><p class="kicker">BOIRSU SCHOOL / TEACHER STUDIO</p><h1>Build the next lesson.</h1><p class="muted">Set the class mode, bring your cohort together, and leave a useful resource behind.</p></div><router-link to="/classroom/teacher" class="launch">Open classroom &rarr;</router-link></header>
    <section class="studio-grid">
      <article class="panel lesson-panel"><div class="panel-head"><div><p class="kicker">LESSON MODE</p><h2>How will you teach today?</h2></div><span class="live-label">{{ mode === 'live' ? 'LIVE VIDEO' : 'YOUTUBE' }}</span></div>
        <div class="mode-switch"><button :class="{active:mode==='live'}" @click="mode='live'">Live video call</button><button :class="{active:mode==='youtube'}" @click="mode='youtube'">YouTube lesson</button></div>
        <div v-if="mode==='live'" class="mode-body"><label>Classroom room <input v-model="course" placeholder="e.g. Python fundamentals" /></label><p class="hint">Students join through the existing cohort classroom. Camera and screen sharing stay available there.</p><button class="primary" @click="openClass">Start live classroom</button></div>
        <div v-else class="mode-body"><label>YouTube video URL <input v-model="videoUrl" placeholder="https://youtube.com/watch?v=..." /></label><label>Lesson title <input v-model="lessonTitle" placeholder="Today’s lesson" /></label><button class="primary" @click="publish">Publish to classroom</button></div>
        <p v-if="notice" class="notice">{{ notice }}</p>
      </article>
      <article class="panel"><p class="kicker">COHORT</p><h2>{{ course || 'Python fundamentals' }}</h2><div class="cohort-stat"><strong>24</strong><span>students enrolled<br><small>18 online now</small></span></div><div class="student-line" v-for="student in students" :key="student.name"><span class="presence"></span>{{ student.name }}<small>{{ student.state }}</small></div></article>
    </section>
    <section class="panel pdf-panel"><div><p class="kicker">RESOURCE BUILDER</p><h2>Create a PDF text lesson</h2><p class="muted">Write notes, exercises or a reading handout and make it available in Student Dashboard.</p></div><div class="pdf-form"><input v-model="pdfTitle" placeholder="Resource title" /><textarea v-model="pdfText" rows="4" placeholder="Write the lesson text here..."></textarea><button class="secondary" @click="createPdf">Create PDF resource &rarr;</button></div><p v-if="pdfNotice" class="notice">{{ pdfNotice }}</p></section>
  </main>
</template>

<script setup>
import { ref } from 'vue'
const mode = ref('live'); const course = ref('Python fundamentals'); const videoUrl = ref(''); const lessonTitle = ref(''); const notice = ref(''); const pdfTitle = ref(''); const pdfText = ref(''); const pdfNotice = ref('')
const students = [{name:'Amara Okafor',state:'Online'},{name:'David Mensah',state:'Online'},{name:'Lilian James',state:'Away'}]
function openClass(){ notice.value = `Opening ${course.value || 'your'} cohort in the live classroom.` }
function publish(){ notice.value = videoUrl.value ? `YouTube lesson ${lessonTitle.value || 'draft'} is ready to publish.` : 'Add a YouTube URL before publishing.' }
function createPdf(){ pdfNotice.value = pdfTitle.value && pdfText.value ? `${pdfTitle.value} is ready for Student Dashboard.` : 'Add a title and lesson text before creating the PDF.' }
</script>

<style scoped>
.portal{min-height:100vh;padding:clamp(28px,5vw,72px);background:#102321;color:#f4f1e8;font-family:'Space Grotesk',system-ui,sans-serif}.top,.studio-grid,.pdf-panel{max-width:1120px;margin:0 auto}.top{display:flex;justify-content:space-between;gap:30px;align-items:flex-end;margin-bottom:40px}.kicker{margin:0 0 10px;color:#e3a65e;font:600 11px monospace;letter-spacing:.14em}.portal h1{margin:0;font:500 clamp(40px,6vw,74px)/.95 Georgia,serif}.muted{max-width:530px;color:#aebcb0;line-height:1.6}.launch,.primary,.secondary{display:inline-block;padding:13px 17px;border:1px solid #e3a65e;background:transparent;color:#f4f1e8;text-decoration:none;cursor:pointer}.studio-grid{display:grid;grid-template-columns:1.35fr .8fr;gap:14px}.panel{padding:28px;background:#183530;border:1px solid #34534a}.panel-head{display:flex;justify-content:space-between;gap:20px;margin-bottom:26px}.panel h2{margin:0;font:500 25px Georgia,serif}.live-label{color:#f2bd72;font:11px monospace}.mode-switch{display:grid;grid-template-columns:1fr 1fr;margin-bottom:26px}.mode-switch button{padding:13px;background:#102b27;border:1px solid #45635b;color:#aebcb0;cursor:pointer}.mode-switch button.active{background:#e3a65e;border-color:#e3a65e;color:#102321}.mode-body{display:grid;gap:15px}label{display:grid;gap:8px;color:#c7d1c7;font-size:13px}input,textarea{width:100%;padding:13px;background:#102b27;border:1px solid #45635b;color:#f4f1e8;font:inherit}textarea{resize:vertical}.primary{background:#e3a65e;border-color:#e3a65e;color:#102321;font-weight:600}.hint{color:#aebcb0;font-size:13px;line-height:1.5}.notice{padding:11px;background:#244d3c;color:#bce0bd;font-size:13px}.cohort-stat{display:flex;gap:14px;align-items:center;margin:26px 0;font-size:13px;color:#aebcb0}.cohort-stat strong{font:500 52px Georgia,serif;color:#e3a65e}.cohort-stat small{color:#bce0bd}.student-line{display:flex;gap:9px;padding:13px 0;border-top:1px solid #34534a;font-size:14px}.student-line small{margin-left:auto;color:#aebcb0}.presence{width:8px;height:8px;margin-top:5px;background:#73c18a;border-radius:50%}.pdf-panel{display:grid;grid-template-columns:.9fr 1.2fr;gap:35px;margin-top:14px}.pdf-form{display:grid;gap:10px}.secondary{justify-self:start}.pdf-panel .notice{grid-column:1/-1}@media(max-width:760px){.portal{padding:26px 18px}.top,.studio-grid,.pdf-panel{display:block}.launch{margin-top:20px}.panel{margin-bottom:14px}.pdf-panel{margin-top:0}.pdf-form{margin-top:22px}}
</style>